version: '3'
services:
  postgresdb:
    restart: always
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    networks:
      - db_network
  aqm:
    restart: always
    env_file: .env
    build: .
    ports:
      - "5005:5005"
    networks:
      - db_network
      - web_network
    depends_on: 
      - postgresdb
  nginx:
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on: 
      - aqm
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass "${REDIS_PASS}"
    ports:
      - "6379:6379"
    networks:
      - web_network
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
volumes: 
  db-data: