# Generated by Django 2.2.10 on 2020-12-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='co',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='no2',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='o3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='so2',
            field=models.FloatField(default=0),
        ),
    ]
