# Generated by Django 2.2.10 on 2020-12-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20201229_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='nh3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='data',
            name='no',
            field=models.FloatField(default=0),
        ),
    ]
